#!/bin/bash

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
CLR="\e[0m"

IPADDR=$(grep -sw 'IPADDR' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')
DOMAIN=$(grep -sw 'DOMAIN' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')
EMAIL=$(grep -sw 'EMAIL' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')
COUNTRY=$(grep -sw 'COUNTRY' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')
STATE=$(grep -sw 'STATE' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')
REGION=$(grep -sw 'REGION' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')
ORG=$(grep -sw 'ORG' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')
UNIT=$(grep -sw 'UNIT' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')
NAME=$(grep -sw 'NAME' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')
PROVIDER=$(grep -sw 'ISP' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')
CONTINENT=$(grep -sw 'CONTINENT' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')
LOCATION=$(grep -sw 'LOCATION' /usr/local/cybertize/.environment | cut -d '=' -f 2 | tr -d '"')

OS=$(hostnamectl | grep -sw 'Operating System' | cut -d ':' -f 2)
KERNEL=$(hostnamectl | grep -sw 'Kernel' | cut -d ':' -f 2)
CPU=$(lscpu | grep -sw 'Model name' | cut -d ':' -f 2 | tr -d ' ')
RAM=$(free --mega -h | awk 'NR==2 {print $2,$3,$4}')
DISK=$(df -h | grep -sw 'vda1' | awk '{print $2,$3,$4}')
BANDWITH=$(vnstat -s -i eth0 | awk 'NR==4' | column -t | awk '{print $9,$10}')
UPTIME=$(uptime -p | awk '{print $2,$3,$4,$5,$6,$7}')

echo
echo -e "${GREEN}            CYBERTIZE SETUP SCRIPT V1.0.0            ${CLR}"
echo
echo -e "${WHITE}=====================================================${CLR}"
echo -e "${BLUE}── █ █▀▀▀█ █▀▀▀ █─▄▀ █▀▀▀ █▀▀█ █▀▀▀█ █── █ █▀▀█ █▄─ █${CLR}"
echo -e "${BLUE}▄─ █ █── █ █▀▀▀ █▀▄─ █▀▀▀ █▄▄▀ ▀▀▀▄▄ ─█ █─ █▄▄█ █ █ █${CLR}"
echo -e "${BLUE}█▄▄█ █▄▄▄█ █▄▄▄ █─ █ █▄▄▄ █─ █ █▄▄▄█ ─▀▄▀─ █─── █──▀█${CLR}"
echo -e "${WHITE}=====================================================${CLR}"
echo
echo -e "${YELLOW}  PROVIDER${CLR}:${GREEN} $ISP ${CLR}"
echo -e "${YELLOW}  LOCATION${CLR}:${GREEN} $LOCATION ${CLR}"
echo -e "${YELLOW}  TIMEZONE${CLR}:${GREEN} $CONTINENT/$LOCATION ${CLR}"
echo -e "${YELLOW} PUBLIC IP${CLR}:${GREEN} $IPADDR ${CLR}"
echo -e "${YELLOW}    DOMAIN${CLR}:${GREEN} $DOMAIN ${CLR}"
echo -e "${YELLOW}        OS${CLR}:${GREEN}$OS ${CLR}"
echo -e "${YELLOW}    KERNEL${CLR}:${GREEN}$KERNEL ${CLR}"
echo -e "${YELLOW}       CPU${CLR}:${GREEN} $CPU ${CLR}"
echo -e "${YELLOW}       RAM${CLR}:${GREEN} $RAM ${CLR}"
echo -e "${YELLOW}      DISK${CLR}:${GREEN} $DISK ${CLR}"
echo -e "${YELLOW}  BANDWITH${CLR}:${GREEN} $BANDWITH Used ${CLR}"
echo -e "${YELLOW}    UPTIME${CLR}:${GREEN} $UPTIME ${CLR}"
echo
echo -e "${WHITE}=====================================================${CLR}"
echo -e "${WHITE}=======[${CLR} ${BLUE}SKRIP OLEH DOCTYPE, HAK CIPTA 2022.${CLR} ${WHITE}]=======${CLR}"
echo -e "${WHITE}=====================================================${CLR}"
echo